### ISSUE TITLE
Project Description Link is Dead

### ISSUE THREAD

**Issue by DavidMuller** [winhamwr/mixpanel-celery#33]
Looks like the [project description link](http://winhamwr.github.io/mixpanel-celery/) is a dead link...

![screen shot 2015-11-20 at 11 30 26 am](https://cloud.githubusercontent.com/assets/4778701/11309689/1fba5580-8f7a-11e5-9632-c2e510272c1b.png)

Would be great if the description linked to the live docs https://mixpanel-celery.readthedocs.org/en/latest/ -- thanks for this package!

**Comment by winhamwr** [comment]
Hi David,

Thanks for filing an issue. Looks like I broke the link when I fiddled with my blog's custom domain. I can't figure out how to not use a custom domain once you've done that for your user account, so linking to the docs looks like the way to go. 

Done.

Thanks again.
-Wes
